from module.graph import Graph

g = Graph()
g.addVert('A')
g.addVert('B')
g.addVert('C')
g.addVert('D')
g.addVert('E')
g.addVert('F')
g.addVert('G')

g.addEdge('A','B',2)
g.addEdge('A','C',3)
g.addEdge('A','D',3)
g.addEdge('B','A',2)
g.addEdge('B','C',4)
g.addEdge('B','E',3)
g.addEdge('C','A',3)
g.addEdge('C','B',4)
g.addEdge('C','D',5)
g.addEdge('C','E',1)
g.addEdge('D','A',3)
g.addEdge('D','C',5)
g.addEdge('D','F',7)
g.addEdge('E','C',1)
g.addEdge('E','B',3)
g.addEdge('E','F',8)
g.addEdge('F','D',7)
g.addEdge('F','E',8)
g.addEdge('F','G',9)
g.addEdge('G','F',9)



#g.printGraph()
#g.graph['A'].printLinkedList()
#g.graph['A'].getMinNode().printNode()
g.getMin().printNode()
